name: Cypress Tests with Install Job and UI Chrome Job x 5


on:
  schedule:
    - cron: '*/5 * * * *'
  push:

jobs:


  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.6.0-chrome105-ff104
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm install




  ui-chrome-tests:

    runs-on: ubuntu-latest
    container: cypress/browsers:node18.6.0-chrome105-ff104
    needs: install
    environment: 
      name: cypress
    strategy: 
      fail-fast: false
      matrix:
        containers: [1,2,3,4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2



      # download cached ~/.npm and ~/.cache/Cypress
      - name: Cypress cache
        uses: cypress-io/github-action@v2
        with: 
          config-file: 'cypress.config.ts'

    
     

      - name: 'UI Tests - Chrome'
       
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          # we have already installed all dependencies above
          install: false      
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/e2e/*
          config-file: 'cypress.config.ts'

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
