name: Cypress Tests with Install Job and a Scheduled Case
on:
  push:
    branches: [canary, clipped-canary]
  schedule:
    - cron: '*/5 * * * *'


   
  
jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.6.0-chrome105-ff104
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
  
      - name: Cypress install
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm install


  ui-chrome-tests:
    name: Catch the Cache of the Cypress then Run the Existency Check for Employee Alias in Amazon Databases
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.6.0-chrome105-ff104
    needs: install
    environment:
      cypress
    steps:
      - name: UI Tests - Checkout a new env
        uses: actions/checkout@v2
        


      # download cached ~/.npm and ~/.cache/Cypress
      - name: UI Tests - Cache the caches
        uses: cypress-io/github-action@v2
        with: 
          config-file: 'cypress.config.ts'


      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          # we have already installed all dependencies above
          install: false      
          browser: chrome
          record: true
          spec: cypress/e2e/*
          config-file: 'cypress.config.ts'

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
